sonar.projectKey=ijava
sonar.projectName=IJava
sonar.sourceEncoding=UTF-8
sonar.sources=src/main/java,basekernel/src/main/java
sonar.tests=src/test/java,basekernel/src/test/java
sonar.java.binaries=build/classes/java/main,basekernel/build/classes/java/main
sonar.java.test.binaries=build/classes/java/test,basekernel/build/classes/java/test
sonar.junit.reportPaths=build/test-results/test,basekernel/build/test-results/test
sonar.exclusions=**/build/**,**/dist/**,**/*.zip,**/*.jar
